name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Login Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # # Set up Docker Buildx
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # # Build and push docker hub
      # - name: Build and push docker hub
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_NAME }}/project_csn:backOfice_1
      
      #Connect SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      

      #Update file
      - name: Update Docker container
        run: |
            sshpass -p @Asdf1@asdf@asdf ssh -o StrictHostKeyChecking=no -p 22 root@128.199.218.147 '
            docker login -u "littleweb14766@gmail.com" -p "warkhem14766"
            docker stop backOfice
            docker rm backOfice
            echo "backOfice_1"
            docker pull littleweb14766/project_csn:backOfice_1
            # docker run -d --name backOfice -p 3000:3000 littleweb14766/project_csn:backOfice_1
            docker-compose up -d
            '



      