name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Login Docker
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push docker hub
      - name: Build and push docker hub
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_NAME }}/project_csn:backOfice_1
  
  deploy:
    runs-on: ubuntu-latest
    # needs: build 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ ติดตั้ง ArgoCD CLI
      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          sudo mv argocd-linux-amd64 /usr/local/bin/argocd
          argocd version --client  # ✅ ตรวจสอบว่า ArgoCD ติดตั้งสำเร็จ

      # ✅ Login เข้า ArgoCD ด้วย Username/Password
      - name: Login to ArgoCD
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} \
            --username ${{ secrets.ARGOCD_USERNAME }} \
            --password ${{ secrets.ARGOCD_PASSWORD }} \
            --insecure --grpc-web --skip-test-tls


      # ✅ Sync Application หลังจาก Build เสร็จ
      - name: Sync ArgoCD Application
        run: |
          argocd app sync backoffice --prune --force
          argocd app wait backoffice --health


      